# Generated by Django 2.2.3 on 2019-07-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
