# Generated by Django 2.2.3 on 2019-07-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasker',
            name='tasker_id',
            field=models.IntegerField(null=True),
        ),
    ]
